.PHONY: all clean test

all: clean test

clean:
	@echo ""
	@echo "--  Cleaning target  ---------------------------------------------------"
	rm -rf target

test:
	@echo ""
	@echo "--  Testing  -----------------------------------------------------------"
